name: Playwright Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run CTRF annotations
        run: npx github-actions-ctrf ctrf/ctrf-report.json
        if: always()

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests and generate report
        run: |
          npx playwright test --reporter=html

      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Publish CTRF Test Summary Results
        run: npx github-actions-ctrf path-to-your-ctrf-report.json
        if: always()
