name: Playwright Tests and Deploy Report to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests and generate report
        run: |
          npx playwright test --reporter=html --output=playwright-report

      - name: Deploy Playwright HTML Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: playwright-report
          publish_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print GitHub Pages URL
        run: |
          echo "Your Playwright Report is available at: https://Manuela-Sousa.github.io/your-repo-name/index.html"
